#!/bin/sh /etc/rc.common

START=99
STOP=15
PIDFILE='/tmp/wss.pid'

TAG="_SS_SPEC_RULE_"

start() {
	if [ -f $PIDFILE ] 
		then
		echo "already started: $PIDFILE exists"
		exit 1
	fi
	flush_r
	rule
	wss.lua >>/dev/null 2>&1 &
	echo $! > $PIDFILE
}

stop() {
	flush_r
    kill `cat $PIDFILE`
    rm $PIDFILE
}


flush_r() {
	flush_iptables() {
		local ipt="iptables -t $1"
		local DAT=$(iptables-save -t $1)
		eval $(echo "$DAT" | grep "$TAG" | sed -e 's/^-A/$ipt -D/' -e 's/$/;/')
		for chain in $(echo "$DAT" | awk '/^:SS_SPEC/{print $1}'); do
			$ipt -F ${chain:1} 2>/dev/null && $ipt -X ${chain:1}
		done
	}
	flush_iptables nat
	flush_iptables mangle

	ipset destroy ss_spec_wan_ac 2>/dev/null
	return 0
}

gen_iplist() { 
	local IGNORE_LIST="/etc/chinaIP.txt"
	# <<EOF 保留所有字符，<<-EOF 去除开头的TAB字符（仅TAB，空格无效）
	# cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
	# 	$(nslookup zengming.herokuapp.com | awk '/^Address\s+\d+:\s+.*?/{print $3}')
	# 	$(nslookup diaozhatian.herokuapp.com | awk '/^Address\s+\d+:\s+.*?/{print $3}')
	# EOF
	cat <<-EOF
		0.0.0.0/8
		10.0.0.0/8
		100.64.0.0/10
		127.0.0.0/8
		169.254.0.0/16
		172.16.0.0/12
		192.0.0.0/24
		192.0.2.0/24
		192.88.99.0/24
		192.168.0.0/16
		198.18.0.0/15
		198.51.100.0/24
		203.0.113.0/24
		224.0.0.0/4
		240.0.0.0/4
		255.255.255.255
		$(cat ${IGNORE_LIST:=/dev/null} 2>/dev/null)
	EOF
}

rule() {
	# 不走代理的ip，如果要让某个IP走代理： 
	# ipset add ss_spec_wan_ac 192.168.1.1 nomatch 
	# 或者
	# ipset del ss_spec_wan_ac 192.168.1.1 
	ipset restore <<-EOF || return 1
		create ss_spec_wan_ac hash:net
		$(gen_iplist | sed -e "s/^/add ss_spec_wan_ac /")
	EOF

	iptables -t nat -N SS_SPEC_WAN_AC
	iptables -t nat -A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
	iptables -t nat -A SS_SPEC_WAN_AC -p tcp -j REDIRECT --to-ports 1088

	iptables -t nat -I PREROUTING  -p tcp -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
	iptables -t nat -I OUTPUT -p tcp -m comment --comment "$TAG" -j SS_SPEC_WAN_AC

	# DNS
	# iptables -t nat -I PREROUTING -m comment --comment "$TAG" -p udp --dport 53 -j DNAT --to :5353
	# iptables -t nat -I PREROUTING -m comment --comment "$TAG" -p tcp --dport 53 -j DNAT --to :5353
	iptables -t nat -I PREROUTING -m comment --comment "$TAG" -p udp --dport 53 -j REDIRECT --to-ports 5353
	iptables -t nat -I PREROUTING -m comment --comment "$TAG" -p tcp --dport 53 -j REDIRECT --to-ports 5353
}




